import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Architecture rules: HTTP and environment access each have exactly one home.
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/lib/api/client.ts"],
    rules: {
      "no-restricted-globals": [
        "error",
        { name: "fetch", message: "Only src/lib/api/client.ts may call fetch." },
      ],
    },
  },
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/lib/config.ts"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector: "MemberExpression[object.name='process'][property.name='env']",
          message: "Only src/lib/config.ts may read process.env.",
        },
      ],
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "coverage/**",
    // Screenshots and diffs written by `npm run test:visual`.
    "visual-results/**",
    // Generated by openapi-typescript (npm run gen:api).
    "src/lib/api/schema.d.ts",
  ]),
]);

export default eslintConfig;
