import react from "@vitejs/plugin-react";
import { fileURLToPath } from "node:url";
import { defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: { "@": fileURLToPath(new URL("./src", import.meta.url)) },
  },
  test: {
    environment: "jsdom",
    setupFiles: ["./src/test/setup.ts"],
    // config.ts validates on load, so the module needs a value to import at all.
    env: { NEXT_PUBLIC_API_URL: "http://localhost:8000" },
    coverage: {
      provider: "v8",
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        // Generated by openapi-typescript: types only, no runtime code.
        "src/lib/api/schema.d.ts",
        // Next.js root layout: renders <html>/<body> and loads next/font, neither of
        // which can be mounted under jsdom. It holds no logic of its own.
        "src/app/layout.tsx",
        // Test infrastructure, not product code.
        "src/test/**",
        "src/**/*.test.{ts,tsx}",
      ],
      thresholds: { lines: 80, functions: 80, branches: 80, statements: 80 },
    },
  },
});
