"""The Attachment entity: something a task points at, a link or a stored file.

Standard library only. An attachment never changes once it exists (it is attached, then
maybe removed), so the entity is frozen and ``__post_init__`` is the one place its rules
are applied, also when a stored attachment is rebuilt.

A link is only ever handed to a browser as an ``href``, so what it may be is decided here
and nowhere else: an absolute ``http`` or ``https`` URL with a host and without credentials.
Everything a browser would run or read locally instead of visiting (``javascript:``,
``data:``, ``file:``) and everything that means something only next to a page (relative
references) is refused.
"""

import re
import uuid
from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum
from typing import Self
from urllib.parse import urlsplit

from app.domain.file_type import FILE_TYPES, FileType
from app.domain.storage_key import valid_storage_key
from app.domain.user import CONTROL_CHARACTERS

URL_MAX_LENGTH = 2000
NAME_MAX_LENGTH = 255
LINK_SCHEMES = ("http", "https")

# Characters that hide in a value or reorder what is shown around them (the bidirectional
# overrides and isolates: "exe.fdp" read as "pdf.exe"), plus the line and paragraph separators.
_HIDDEN = rf"{CONTROL_CHARACTERS}\u200e\u200f\u2028\u2029\u202a-\u202e\u2066-\u2069"
HIDDEN_CHARACTER = re.compile(rf"[{_HIDDEN}]")
_NOT_IN_A_URL = re.compile(rf"[\s{_HIDDEN}]")


class InvalidAttachmentError(ValueError):
    """An attachment would break one of its rules."""


class AttachmentKind(StrEnum):
    """The design's three kinds. ``link`` has a URL; ``pdf`` and ``image`` are stored files."""

    LINK = "link"
    PDF = "pdf"
    IMAGE = "image"


@dataclass(frozen=True, slots=True)
class Attachment:
    id: uuid.UUID
    task_id: uuid.UUID
    kind: AttachmentKind
    # What people see. For a file it is the client's file name, sanitised: display metadata
    # only, never a path and never part of where the file is stored.
    name: str
    created_by: uuid.UUID
    created_at: datetime
    url: str | None = None
    # Where the file lives in the ``FileStorage``: generated by the server, never shown.
    storage_key: str | None = None
    content_type: str | None = None
    size_bytes: int | None = None

    def __post_init__(self) -> None:
        _check_name(self.name)
        if self.created_at.utcoffset() is None:
            raise InvalidAttachmentError("timestamps must be timezone-aware")
        file_fields = (self.storage_key, self.content_type, self.size_bytes)
        if self.kind is AttachmentKind.LINK:
            if self.url is None or any(field is not None for field in file_fields):
                raise InvalidAttachmentError("a link has a url and no stored file")
            _check_url(self.url)
            return
        if self.url is not None or any(field is None for field in file_fields):
            raise InvalidAttachmentError(
                "a file has a storage key, a content type and a size, and no url"
            )
        # ``bool`` is an ``int`` in Python; ``True`` is not a size.
        if type(self.size_bytes) is not int or self.size_bytes <= 0:
            raise InvalidAttachmentError("size_bytes must be a positive whole number")

        file_type = next((t for t in FILE_TYPES if t.content_type == self.content_type), None)
        if file_type is None or file_type.is_image != (self.kind is AttachmentKind.IMAGE):
            raise InvalidAttachmentError("kind and content_type must match an allowed file type")
        if not valid_storage_key(self.storage_key or ""):
            raise InvalidAttachmentError("invalid storage key")

    @classmethod
    def file(
        cls,
        *,
        attachment_id: uuid.UUID,
        task_id: uuid.UUID,
        file_name: str | None,
        file_type: FileType,
        storage_key: str,
        size_bytes: int,
        created_by: uuid.UUID,
        now: datetime,
    ) -> Self:
        name = (file_name or "").replace("\\", "/").split("/")[-1]
        name = " ".join(HIDDEN_CHARACTER.sub("", name).split()).strip(" .") or "file"
        extension = next((ext for ext in file_type.extensions if name.lower().endswith(ext)), None)
        if extension is None:
            extension = file_type.extension
            name += extension
        if len(name) > NAME_MAX_LENGTH:
            name = name[: NAME_MAX_LENGTH - len(extension)] + extension
        return cls(
            id=attachment_id,
            task_id=task_id,
            kind=AttachmentKind.IMAGE if file_type.is_image else AttachmentKind.PDF,
            name=name,
            created_by=created_by,
            created_at=now,
            storage_key=storage_key,
            content_type=file_type.content_type,
            size_bytes=size_bytes,
        )

    @classmethod
    def link(
        cls,
        *,
        attachment_id: uuid.UUID,
        task_id: uuid.UUID,
        url: str,
        name: str | None,
        created_by: uuid.UUID,
        now: datetime,
    ) -> Self:
        """A link, named after its host unless the caller names it."""
        address = url.strip()
        host = _check_url(address)
        return cls(
            id=attachment_id,
            task_id=task_id,
            kind=AttachmentKind.LINK,
            name=(name or "").strip() or host,
            created_by=created_by,
            created_at=now,
            url=address,
        )

    @property
    def is_file(self) -> bool:
        return self.kind is not AttachmentKind.LINK


def _check_name(name: str) -> None:
    if not name or name != name.strip():
        raise InvalidAttachmentError("name must not be blank or padded with whitespace")
    if len(name) > NAME_MAX_LENGTH:
        raise InvalidAttachmentError(f"name must be at most {NAME_MAX_LENGTH} characters")
    if HIDDEN_CHARACTER.search(name):
        raise InvalidAttachmentError("name must not contain control or direction characters")


def _check_url(url: str) -> str:
    """The host (``example.com``, ``localhost:8000``) of a URL a task may link to.

    Raises ``InvalidAttachmentError``. The message never repeats the URL: a refused one may
    carry a password.
    """
    if not url:
        raise InvalidAttachmentError("url must not be blank")
    if len(url) > URL_MAX_LENGTH:
        raise InvalidAttachmentError(f"url must be at most {URL_MAX_LENGTH} characters")
    if _NOT_IN_A_URL.search(url) or "\\" in url:
        raise InvalidAttachmentError(
            "url must not contain whitespace, backslashes or control characters"
        )
    try:
        parts = urlsplit(url)
        host, port = parts.hostname, parts.port
    except ValueError:
        raise InvalidAttachmentError("url is not a valid URL") from None
    if parts.scheme.lower() not in LINK_SCHEMES:
        raise InvalidAttachmentError("url must be an absolute http or https URL")
    if "@" in parts.netloc:
        raise InvalidAttachmentError("url must not carry a user name or a password")
    if not host:
        raise InvalidAttachmentError("url must name a host")
    shown = f"[{host}]" if ":" in host else host
    return shown if port is None else f"{shown}:{port}"
